version: '3.5'

services:
  omada-controller:
    build:
      context: .  # Builds the image from the Dockerfile in the current directory
    container_name: omada-controller
    ports:
      - "8088:8088"
      - "8043:8043"
      - "8843:8843"
      - "29810:29810/udp"
      - "29811:29811"
      - "29812:29812"
      - "29813:29813"
      - "29814:29814"
    volumes:
      - omada-data:/opt/tplink/EAPController/data  # Persist Omada data
      - omada-logs:/opt/tplink/EAPController/logs # Persist logs
    environment:
      - INSTALL_DIR=/opt/tplink/EAPController
    restart: unless-stopped

# Volumes to persist data between container restarts
volumes:
  omada-data:
  omada-logs: